/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package TodoApp;

import java.sql.Connection;
import util.ConnectionFactory;
import model.Project;
import controler.ProjectController;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
     /* Connection c = ConnectionFactory.getConnection();
      ConnectionFactory.closeConnection(c);*/
     
     ProjectController projectController = new ProjectController();
     
     Project project = new Project();
     project.setName("Projeto Teste");
     project.setDescription("describe");
     projectController.save(project);
     
       /* List<Project> projects = projectController.getAll();
        System.out.println(projects);*/
     
    }
}
